/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsIdRouteImport } from './routes/markets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIdRoute = MarketsIdRouteImport.update({
  id: '/markets/$id',
  path: '/markets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/positions': typeof PositionsRoute
  '/swap': typeof SwapRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/watchlist': typeof WatchlistRoute
  '/withdraw': typeof WithdrawRoute
  '/markets/$id': typeof MarketsIdRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/positions': typeof PositionsRoute
  '/swap': typeof SwapRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/watchlist': typeof WatchlistRoute
  '/withdraw': typeof WithdrawRoute
  '/markets/$id': typeof MarketsIdRoute
  '/markets': typeof MarketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/positions': typeof PositionsRoute
  '/swap': typeof SwapRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/watchlist': typeof WatchlistRoute
  '/withdraw': typeof WithdrawRoute
  '/markets/$id': typeof MarketsIdRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/positions'
    | '/swap'
    | '/tools'
    | '/trade'
    | '/watchlist'
    | '/withdraw'
    | '/markets/$id'
    | '/markets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/positions'
    | '/swap'
    | '/tools'
    | '/trade'
    | '/watchlist'
    | '/withdraw'
    | '/markets/$id'
    | '/markets'
  id:
    | '__root__'
    | '/'
    | '/positions'
    | '/swap'
    | '/tools'
    | '/trade'
    | '/watchlist'
    | '/withdraw'
    | '/markets/$id'
    | '/markets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PositionsRoute: typeof PositionsRoute
  SwapRoute: typeof SwapRoute
  ToolsRoute: typeof ToolsRoute
  TradeRoute: typeof TradeRoute
  WatchlistRoute: typeof WatchlistRoute
  WithdrawRoute: typeof WithdrawRoute
  MarketsIdRoute: typeof MarketsIdRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$id': {
      id: '/markets/$id'
      path: '/markets/$id'
      fullPath: '/markets/$id'
      preLoaderRoute: typeof MarketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PositionsRoute: PositionsRoute,
  SwapRoute: SwapRoute,
  ToolsRoute: ToolsRoute,
  TradeRoute: TradeRoute,
  WatchlistRoute: WatchlistRoute,
  WithdrawRoute: WithdrawRoute,
  MarketsIdRoute: MarketsIdRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
